//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroDeIdiomas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        public int Id { get; set; }
        public string Nombre_Libro { get; set; }
        public string Nombre_Autor { get; set; }
        public string Categoria { get; set; }
    }
}
