//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroDeIdiomas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO
    {
        public int Id_Registro { get; set; }
        public string NUM_CONTROL { get; set; }
        public string Nombre_Alumno { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
